ExamenComicsMario/Models/Comic.cs
namespace ExamenComicsMario.Models
{
    public class Comic
    {
        public int IdComic {  get; set; }
        public string Nombre { get; set; }
        public string Imagen { get; set; }
        public string Descripcion { get; set; }
    }
}

ExamenComicsMario/Models/ErrorViewModel.cs
namespace ExamenComicsMario.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExamenComicsMario/Controllers/ComicsController.cs
using System.Diagnostics;
using System.Numerics;
using ExamenComicsMario.Models;
using ExamenComicsMario.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace ExamenComicsMario.Controllers
{
    public class ComicsController : Controller
    {
        private RepositoryComics repo;

        public ComicsController()
        {
            this.repo = new RepositoryComics();
        }
        public IActionResult Index()
        {
            List<Comic> comics = this.repo.GetComics();
            return View(comics);
        }

        public IActionResult Crear()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Crear(Comic comic)
        {
            this.repo.InsertComic(comic);
            return RedirectToAction("Index");
        }

        public IActionResult Buscar()
        {
            ViewData["COMICS"] = this.repo.GetNombresComics();
            return View();
        }

        [HttpPost]
        public IActionResult Buscar(string comic)
        {
            ViewData["COMICS"] = this.repo.GetNombresComics();
            Comic comic1 = this.repo.GetDetalleComic(comic);
            return View(comic1);
        }
    }
}

ExamenComicsMario/Views/Comics/Buscar.cshtml
@model Comic

@{
    List<string> nombres = (List<string>)ViewData["COMICS"];
}

<h1 style="color: red;">
    Detalles Cómic Seleccionado
</h1>

<form method="post" id="comicForm">
    <label>Nombre cómic</label>
    <select name="comic" class="form-control" id="comicForm" onchange="document.getElementById('comicForm').submit();">
        @foreach(string com in nombres){
            <option value="@com">@com</option>
        }
    </select>
    @* <button class="btn btn-info">Buscar detalle cómic</button> *@
</form>

@if(Model != null){
    <div class="col-md-4">
        <div class="card mb-3" style="width: 18rem;">
            <img src="@Model.Imagen" class="card-img-top" alt="@Model.Nombre">
            <div class="card-body">
                <h5 class="card-title">@Model.Nombre</h5>
                <h6 class="card-subtitle">@Model.IdComic</h6>
                <p class="card-text">@Model.Descripcion</p>
            </div>
        </div>
    </div>
}

ExamenComicsMario/Views/Comics/Crear.cshtml
<h1>Create</h1>
<h2>Comic</h2>
<hr />
<form method="post">
    <input type="hidden" name="idcomic" class="form-control" />
    <label>Nombre </label>
    <input type="text" name="nombre" class="form-control" />
    <label>Imagen </label>
    <input type="text" name="imagen" class="form-control" />
    <label>Descripción </label>
    <input type="text" name="descripcion" class="form-control" />
    <button class="btn btn-primary">
        Create
    </button>
</form>

<p>
    <a asp-controller="Comics"
       asp-action="Index"
       class="btn btn-secondary">
        Back to List
    </a>
</p>

ExamenComicsMario/Views/Comics/Index.cshtml
@model List<Comic>

<h1 style="color: blue;">
    Comics SQL y Oracle
</h1>

@Html.ActionLink("Create New", "Crear")

<div class="container">
    <div class="row">
        @foreach (Comic comic in Model)
        {
            <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
                <div class="card h-100">
                    <img src="@comic.Imagen" class="card-img-top" alt="@comic.Nombre">
                    <div class="card-body">
                        <h5 class="card-title">@comic.Nombre</h5>
                        <p class="card-text">@comic.Descripcion</p>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

ExamenComicsMario/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExamenComicsMario</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExamenComicsMario.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <img src="~/images/peterporker.8f99499b.png" style="width: 50px; height: 50px;" />
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Comics" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-bg-light" asp-area="" asp-controller="Comics" asp-action="Crear">Create New</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-bg-light" asp-area="" asp-controller="Comics" asp-action="Buscar">Buscar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ExamenComicsMario - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>